app:
  jwtSecret: Aslkdjalwidjaslmdnmcnvxleflisdjflskejflidsjflskjefasdsadsadasdqweqewqe123asdsadzxczcadw
  googleClientId: "your-google-client-id"

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1.;DB_CLOSE_ON_EXIT=FALSE;
    username: SA
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect